
project_id = "yztozysvxyjqguybokqj"

[functions.ai-agent]
verify_jwt = true

[functions.ai-brain-ingest]
verify_jwt = true

[functions.ai-brain-query]
verify_jwt = true

[functions.ai-brain-reindex]
verify_jwt = true
