
import { Lead } from '@/types/lead';

export const useLeadData = () => {
  const leads: Lead[] = [
    { 
      id: '1', 
      name: "Michael Scott", 
      company: "Dunder Mifflin", 
      source: "LinkedIn", 
      score: 85, 
      priority: 'high',
      sentiment: 'positive',
      objection: 'Needs approval',
      email: 'michael@dundermifflin.com',
      phone: '(570) 555-1234',
      status: 'new',
      tags: ['Budget Approved'],
      isSensitive: false,
      conversionLikelihood: 78,
      notes: 'Very interested in our platform',
      lastContact: '2024-01-15T10:00:00Z',
      value: 50000
    },
    { 
      id: '2', 
      name: "Jim Halpert", 
      company: "Athlead", 
      source: "Facebook", 
      score: 72, 
      priority: 'medium', 
      lastContact: '2024-01-12T09:30:00Z',
      sentiment: 'neutral',
      objection: 'Price concern',
      email: 'jim@athlead.com',
      phone: '(570) 555-5678',
      status: 'contacted',
      tags: ['Price Sensitive'],
      isSensitive: false,
      conversionLikelihood: 62,
      notes: 'Needs technical demo',
      value: 35000
    },
    { 
      id: '3', 
      name: "Pam Beesly", 
      company: "Pratt Institute", 
      source: "Referral", 
      score: 93, 
      priority: 'high',
      sentiment: 'positive',
      email: 'pam@pratt.edu',
      phone: '(570) 555-9012',
      status: 'qualified',
      tags: ['Hot Lead', 'Demo Scheduled'],
      isSensitive: false,
      conversionLikelihood: 89,
      notes: 'Ready to move forward',
      lastContact: '2024-01-14T11:20:00Z',
      value: 75000
    },
    { 
      id: '4', 
      name: "Dwight Schrute", 
      company: "Schrute Farms", 
      source: "Website", 
      score: 68, 
      priority: 'medium', 
      lastContact: '2024-01-10T15:45:00Z',
      sentiment: 'negative',
      objection: 'Current provider',
      email: 'dwight@schrutefarms.com',
      phone: '(570) 555-3456',
      status: 'new',
      tags: ['Existing Provider'],
      isSensitive: false,
      conversionLikelihood: 45,
      notes: 'Needs competitor comparison',
      value: 40000
    },
    { 
      id: '5', 
      name: "Ryan Howard", 
      company: "WUPHF.com", 
      source: "LinkedIn", 
      score: 64, 
      priority: 'low', 
      lastContact: '2024-01-11T14:30:00Z',
      sentiment: 'neutral',
      objection: 'No budget',
      email: 'ryan@wuphf.com',
      phone: '(570) 555-7890',
      status: 'contacted',
      tags: ['Budget Constraints'],
      isSensitive: false,
      conversionLikelihood: 32,
      notes: 'Early stage inquiry',
      value: 25000
    },
  ];

  return { leads };
};
