
import { Lead } from '@/types/lead';

export const useMockData = () => {
  const leads: Lead[] = [
    {
      id: '1',
      name: 'Sarah Chen',
      email: 'sarah.chen@techcorp.com',
      phone: '+1-555-0123',
      company: 'TechCorp',
      status: 'proposal',
      priority: 'high',
      source: 'LinkedIn',
      score: 94,
      conversionLikelihood: 86,
      lastContact: '2024-01-15T10:00:00Z',
      speedToLead: 2,
      tags: ['enterprise', 'hot lead'],
      createdAt: '2024-01-10T09:00:00Z',
      updatedAt: '2024-01-15T10:00:00Z',
      companyId: 'demo-company',
      isSensitive: false,
      value: 94760,
      lastActivity: 'No reply in 4 days',
      aiPriority: 'high',
      nextAction: 'Reschedule call',
      lastAIInsight: 'No reply in 4 days – reschedule now'
    },
    {
      id: '2',
      name: 'Mike Rodriguez',
      email: 'mike.rodriguez@startupx.com',
      phone: '+1-555-0124',
      company: 'StartupX',
      status: 'negotiation',
      priority: 'high',
      source: 'Referral',
      score: 87,
      conversionLikelihood: 82,
      lastContact: '2024-01-14T15:30:00Z',
      speedToLead: 1,
      tags: ['decision maker', 'budget approved'],
      createdAt: '2024-01-08T14:00:00Z',
      updatedAt: '2024-01-14T15:30:00Z',
      companyId: 'demo-company',
      isSensitive: false,
      value: 78500,
      lastActivity: 'Opened proposal twice',
      aiPriority: 'high',
      nextAction: 'Follow up on proposal',
      lastAIInsight: 'Opened proposal twice, no reply'
    },
    {
      id: '3',
      name: 'Lisa Wang',
      email: 'lisa.wang@enterprise.co',
      phone: '+1-555-0125',
      company: 'Enterprise Co',
      status: 'qualified',
      priority: 'high',
      source: 'Website',
      score: 76,
      conversionLikelihood: 74,
      lastContact: '2024-01-13T09:15:00Z',
      speedToLead: 3,
      tags: ['demo requested', 'technical buyer'],
      createdAt: '2024-01-09T11:00:00Z',
      updatedAt: '2024-01-13T09:15:00Z',
      companyId: 'demo-company',
      isSensitive: false,
      value: 65200,
      lastActivity: 'Last call 6 days ago',
      aiPriority: 'medium',
      nextAction: 'Schedule demo',
      lastAIInsight: 'Last call 6 days ago – follow-up recommended'
    },
    {
      id: '4',
      name: 'David Kim',
      email: 'david.kim@globalsoft.com',
      phone: '+1-555-0126',
      company: 'GlobalSoft',
      status: 'contacted',
      priority: 'medium',
      source: 'Cold Email',
      score: 71,
      conversionLikelihood: 68,
      lastContact: '2024-01-12T14:45:00Z',
      speedToLead: 4,
      tags: ['interested', 'budget questions'],
      createdAt: '2024-01-07T16:30:00Z',
      updatedAt: '2024-01-12T14:45:00Z',
      companyId: 'demo-company',
      isSensitive: false,
      value: 52300,
      lastActivity: 'Clicked demo link',
      aiPriority: 'medium',
      nextAction: 'Book demo call',
      lastAIInsight: 'Clicked demo link, but didn\'t book'
    },
    {
      id: '5',
      name: 'Jennifer Lee',
      email: 'jennifer.lee@cloudfirst.com',
      phone: '+1-555-0127',
      company: 'CloudFirst',
      status: 'new',
      priority: 'medium',
      source: 'Trade Show',
      score: 69,
      conversionLikelihood: 65,
      lastContact: '2024-01-11T11:20:00Z',
      speedToLead: 2,
      tags: ['new contact', 'interested'],
      createdAt: '2024-01-11T11:20:00Z',
      updatedAt: '2024-01-11T11:20:00Z',
      companyId: 'demo-company',
      isSensitive: false,
      value: 41800,
      lastActivity: 'Initial contact made',
      aiPriority: 'low',
      nextAction: 'Qualification call',
      lastAIInsight: 'New lead, strong initial interest'
    }
  ];

  const getLeadById = (id: string): Lead | undefined => {
    return leads.find(lead => lead.id === id);
  };

  return {
    leads,
    getLeadById
  };
};
